"""
Natural, real-world-style civic complaint texts.
Written to mimic how actual citizens type complaints on portals — 
with varied tone, informal grammar, abbreviations, and urgency levels.
"""

NATURAL_COMPLAINTS = {
    'damaged_road': [
        "Road is completely broken, my car suspension got damaged yesterday",
        "The road surface has been torn up for months and nobody is fixing it",
        "After the rains the road near our colony is full of cracks and broken tar",
        "The road is in pathetic condition, buses can't even pass properly",
        "Sir the road between the two colonies has been dug up and never repaired",
        "Bad road condition causing daily problems for school children and autorickshaws",
        "Road surface peeling off dangerously, motorcyclists are falling regularly",
        "Main highway road damaged after construction work, tiles coming out",
        "Please repair the broken road, its been 6 months since complaint",
        "entire stretch of road is in shambles, no proper surface left",
        "road has been destroyed due to continuous heavy vehicle movement",
        "asphalt road crumbling apart in our area, very dangerous for two wheelers",
        "damaged tar road after pipeline work, contractor did not restore it properly",
        "road condition worsening day by day, urgent repair needed before monsoon",
        "the road near bridge has developed major cracks, vehicles are getting stuck",
        "badly maintained road full of bumps and uneven patches",
        "neglected road maintenance causing accidents almost every week",
        "road destruction noticed near the government school boundary wall area",
        "the highway road surface is full of dents and broken patches",
        "broken road near bus stand causing flat tyres for autos and cars daily",
    ],
    'pothole': [
        "Massive pothole on the main road, someone already had an accident there",
        "there are so many potholes i cant drive without zigzagging through them",
        "A pothole the size of a tyre is right in the middle of busy intersection",
        "pothole filled with muddy water, bikes keep skidding on it",
        "please fix the pothole infront of our gate, my mother fell into it",
        "Small pothole has become a crater now, rainwater collects in it",
        "Numerous potholes on the road leading to hospital, ambulances struggling",
        "pothole causing traffic jam everyday because everyone tries to avoid it",
        "the pothole near school is very deep, children walking around it on road",
        "Huge pothole appeared after last night rains, need immediate filling",
        "crater sized pothole near market, three accidents this month already",
        "new potholes forming on recently laid road, poor quality construction",
        "dangerous pothole hidden under water during rains, two wheeler danger",
        "pothole near hospital entrance needs urgent repair, patients suffering",
        "giant pothole makes driving impossible at night without streetlights",
        "road full of potholes from main chowk to railway station",
        "pothole fixed last month has opened up again, waste of taxpayer money",
        "deep potholes on residential road, even walking is difficult",
        "small potholes multiplying rapidly near our society gate",
        "pothole on highway so big that a rickshaw wheel got stuck in it",
    ],
    'littering': [
        "Garbage not collected since 1 week, its stinking badly",
        "people are throwing waste in open plot next to our house",
        "garbage dump near school gate, children exposed to diseases",
        "municipal workers not picking up garbage from our lane",
        "plastic waste piled up near the river, polluting the water",
        "garbage bins overflowing for 3 days, dogs tearing bags apart",
        "construction debris dumped on public road blocking the lane",
        "somebody dumped household waste on the footpath overnight",
        "trash all over the park, nobody cleaning it up, children cant play",
        "garbage collector hasnt come for 10 days now, unbearable smell",
        "empty plot being used as garbage dump, mosquitoes breeding",
        "waste scattered everywhere near bus stop, tourists getting bad impression",
        "garbage truck skipping our colony for past one week",
        "food waste being dumped openly near restaurant row, rat infestation",
        "medical waste found dumped near residential area, biohazard concern",
        "overflowing community bins creating health emergency in our ward",
        "commercial waste being thrown in residential streets every night",
        "dumping of household garbage in nalla causing blockage",
        "litter problem near beach area getting worse, plastic everywhere",
        "garbage segregation not being followed, everything mixed up",
    ],
    'water_supply': [
        "No water since yesterday morning, entire locality is suffering",
        "water comes for only 15 minutes in morning, not enough to fill buckets",
        "brown muddy water is coming from tap, not fit for drinking",
        "water pipeline broken near my house, water is being wasted",
        "we dont get any water on 3rd floor due to low pressure",
        "water supply timing changed without notice, missed filling tanks",
        "bore well dried up, need municipal water tanker urgently",
        "contaminated water supply giving stomach infection to children",
        "water not coming at all in our apartment since 2 days",
        "pipeline leaking badly since last week, water wasted on road",
        "water pressure extremely low, cant even wash clothes",
        "no water supply in our building, had to buy water cans",
        "rusty water from taps, concerned about health effects",
        "water tanker not arriving despite repeated complaints",
        "main water line burst near market, road flooded",
    ],
    'drainage': [
        "drain overflowing during every rain, water entering our house",
        "open nala near our house is a breeding ground for mosquitoes",
        "drain cover broken, a child almost fell into it last week",
        "drainage system completely blocked, sewage water on road",
        "rainwater logging on main road due to choked drains",
        "storm water drain not cleaned before monsoon, flooding guaranteed",
        "stagnant water in drain attracting mosquitoes, dengue risk",
        "drainage pipe burst under road, water seeping everywhere",
        "blocked drains causing waterlogging in basement",
        "open drain near school is hazardous, need to cover immediately",
        "drainage overflow causing foul smell in neighborhood",
        "clogged drain near market making road slushy and slippery",
        "underground drainage pipe collapsed, road sinking",
        "no proper drainage in our colony, streets flood every monsoon",
        "gutter water mixing with drinking water line, health emergency",
    ],
    'electricity': [
        "No power since 3 days, food spoiling in fridge",
        "street light not working for 2 months, road is pitch dark",
        "transformer making buzzing noise and sparks visible, scary",
        "power keeps tripping every 30 minutes, electronics damaged",
        "electric meter changed but supply not restored, its a week",
        "entire area facing load shedding daily for 4+ hours",
        "street lights on during day but off at night, timer issue",
        "no electricity in hospital ward, patients suffering",
        "power supply fluctuating badly, appliances getting damaged",
        "broken street light pole lying on road since last month",
        "area gets complete blackout whenever it rains",
        "power outage complaint registered 5 times, no visit yet",
        "street light flickering continuously, disturbing residents",
        "electricity bill very high despite low usage, meter issue",
        "newly installed smart meter not working, wrong readings",
    ],
    'fallen_trees': [
        "Big tree fell on the road after storm blocking traffic",
        "tree branch fell on parked car, need compensation",
        "Old tree is tilting dangerously, could fall on house",
        "tree roots lifting the pavement and footpath, tripping people",
        "tree fell on electric wire, wire could snap anytime",
        "large tree blocking the only road to our colony after cyclone",
        "dead tree standing near children park, could fall on kids",
        "heavy tree branch hanging loose, about to break off",
        "tree uprooted during heavy rain, no one cleared it",
        "multiple trees fell after windstorm, roads impassable",
        "decaying tree near school should be removed before it falls",
        "tree fell on boundary wall and damaged it completely",
        "coconut tree leaning over road, dangerous for vehicles",
        "fallen tree debris lying on road after a week",
        "tree fell on power transformer, area without electricity",
    ],
    'illegal_parking': [
        "Cars double parked on both sides every evening, cant pass",
        "commercial vehicles on residential road overnight illegally",
        "somebody abandoned a truck in no parking zone for a month",
        "bikes parked all over footpath, pedestrians on road",
        "auto rickshaws blocked entire lane near station illegally",
        "construction vehicles parked on main road blocking traffic",
        "vehicles parked in front of fire hydrant, safety hazard",
        "delivery trucks double parked outside shops all day",
        "illegally parked cars blocking ambulance access to hospital",
        "motorbikes parked on pedestrian crossing zebra lines",
        "car blocking our building driveway, cant take our car out",
        "no parking sign visible but vehicles still parked daily",
        "vehicle owners parking on garden strip, damaging area",
        "heavy vehicles near school zone creating congestion",
        "abandoned vehicle rusting on road for several months",
    ],
    'vandalism': [
        "someone broke park bench and public water fountain",
        "graffiti painted on freshly renovated government building",
        "bus shelter glass panels smashed by miscreants",
        "public toilet door broken and mirror smashed, unusable",
        "street name boards pulled out, no direction indicators",
        "someone damaged all saplings planted by municipality",
        "playground equipment broken deliberately by hooligans",
        "public dustbins uprooted and thrown around the area",
        "historical monument wall defaced with spray paint",
        "road divider railing bent and broken by someone",
        "community hall furniture destroyed by unknown people",
        "park fencing cut open and stolen, area now insecure",
        "newly installed solar street lights vandalized",
        "public seating area near lake completely destroyed",
        "public library notice board torn and scattered",
    ],
    'damaged_concrete': [
        "Footpath concrete breaking apart, elderly people tripping",
        "bridge railing concrete crumbling, exposed iron visible",
        "building wall concrete chunks falling on pedestrians",
        "overpass concrete deterioration, reinforcement bars rusting",
        "compound wall concrete damaged, could collapse in rains",
        "flyover pillar showing cracks, structural concern",
        "concrete steps of public stairway broken and uneven",
        "retaining wall concrete cracked after heavy rains",
        "concrete pavement in market broken into loose pieces",
        "underpass ceiling concrete peeling, pieces falling on road",
        "concrete platform at bus stand crumbling, unfit to sit",
        "parking structure concrete showing deep cracks, unsafe",
        "school compound wall concrete falling apart",
        "pedestrian bridge concrete railing in bad condition",
        "public swimming pool deck concrete damaged and chipped",
    ],
    'broken_road_sign': [
        "stop sign missing at busy crossing, daily near-misses",
        "speed limit board broken near school, vehicles speeding",
        "traffic signal not working at major junction causing chaos",
        "no entry sign faded and unreadable, wrong way driving",
        "direction sign board fell during storm, tourists lost",
        "highway exit sign damaged, drivers missing their exits",
        "road curve warning sign missing, accidents frequently",
        "pedestrian crossing sign knocked down, not replaced",
        "school zone slow down sign not visible, needs replacement",
        "one way sign removed, two way traffic causing chaos",
        "traffic board at roundabout damaged, still not fixed",
        "hospital ahead sign damaged, emergency vehicles lost",
        "railway crossing warning sign broken, very dangerous",
        "road closed diversion sign missing, entering dead end",
        "parking zone sign board about to fall on road",
    ],
    'dead_animal': [
        "Dead cow lying on road for 2 days, nobody removing it",
        "stray dog found dead near park, body decomposing",
        "dead bird near water tank, worried about contamination",
        "animal carcass on highway causing terrible smell",
        "roadkill not cleaned for days, maggots visible",
        "dead cat found near school, children are scared",
        "cow carcass blocking half the road, traffic diverting",
        "dead animal near water source, disease risk",
        "decomposed animal body attracting vultures",
        "dead animal in drainage channel causing blockage",
        "animal carcass attracting aggressive stray dogs",
        "dead animal smell impossible to sit on balcony",
        "found dead animal near children playground",
        "body of dead snake on footpath near market",
        "hit and run animal on highway since morning",
    ],
    'damaged_electric_wires': [
        "Electric wire hanging low, could touch passing truck",
        "sparking from damaged pole at night, very dangerous",
        "broken electric pole leaning on tree, wires tangled",
        "live wire fell on road after storm, cordoned off",
        "exposed cable junction box open, children play nearby",
        "electric pole tilted 45 degrees, about to fall",
        "transformer wires hanging loose, crackling in rain",
        "cable insulation melted, bare copper wire exposed",
        "street light pole wire dangling, pedestrians in danger",
        "high tension wire sagging low over road after storm",
        "damaged underground cable sparking through manhole",
        "electrical fire smell from damaged wiring on pole",
        "power line touching metal roof, electrocution risk",
        "broken insulator causing wire to sag into tree",
        "electric wire entangled with branches, sparking",
    ],
    'sewage': [
        "Manhole overflowing with sewage in front of house",
        "sewer line burst flooding lane with dirty water",
        "sewage water mixing with drinking water, people sick",
        "manhole cover broken, open pit of sewage on road",
        "sewage smell so strong cant keep windows open",
        "raw sewage discharged into river near our area",
        "basement flooded with sewage water in apartment",
        "sewer pipeline blocked causing backflow into toilets",
        "sewage treatment plant not working, untreated water",
        "child fell into uncovered manhole, still not covered",
        "sewage overflow during rains flooding intersection",
        "cracked sewer pipe leaking into groundwater",
        "public toilet sewage flowing onto main road",
        "old sewage system collapsed, needs replacement",
        "sewage water stagnating near hospital, mosquitoes",
    ],
    'other': [
        "Construction noise at 2am not letting anyone sleep",
        "Stray dogs becoming aggressive, chasing people",
        "Public toilet horrible condition, no water no maintenance",
        "Footpath encroached by street vendors, cant walk",
        "Illegal construction happening without permission",
        "Factory chimney releasing black smoke, poor air",
        "mosquito fogging not done since months, dengue rising",
        "noise from marriage hall loudspeakers past midnight",
        "unauthorized hawkers taken over walking path",
        "air pollution from burning garbage by factory",
        "stray cattle roaming on highway causing accidents",
        "public bench in park needs repair",
        "food stalls creating fire hazard near petrol pump",
        "fly tipping and soil dumping near colony entrance",
        "ongoing illegal mining near river bank area",
    ],
}
