const { supabaseAdmin } = require('../models/supabaseClient');
const axios = require('axios');

const ML_URL = process.env.ML_SERVICE_URL || 'http://localhost:8000';

/**
 * POST /api/cctv/streams — Add a stream
 */
exports.addStream = async (req, res, next) => {
  try {
    const { name, stream_url, stream_type, latitude, longitude } = req.body;

    if (!name || !stream_url) {
      return res.status(400).json({ error: 'name and stream_url are required' });
    }

    const { data, error } = await supabaseAdmin
      .from('cctv_streams')
      .insert({
        name,
        stream_url,
        stream_type: stream_type || 'http',
        latitude: latitude ? parseFloat(latitude) : null,
        longitude: longitude ? parseFloat(longitude) : null
      })
      .select()
      .single();

    if (error) return res.status(500).json({ error: error.message });

    res.status(201).json({ message: 'Stream added', stream: data });
  } catch (err) { next(err); }
};

/**
 * GET /api/cctv/streams — List all streams
 */
exports.getStreams = async (req, res, next) => {
  try {
    const { data, error } = await supabaseAdmin
      .from('cctv_streams')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) return res.status(500).json({ error: error.message });

    res.json({ streams: data || [] });
  } catch (err) { next(err); }
};

/**
 * POST /api/cctv/analyze — Trigger frame analysis from stream URL or uploaded image
 */
exports.analyzeFrame = async (req, res, next) => {
  try {
    const { stream_id, image_url, frame_data } = req.body;

    if (!stream_id) return res.status(400).json({ error: 'stream_id is required' });

    // Try to get frame from stream URL if no image_url given
    let analysisUrl = image_url;

    if (!analysisUrl) {
      // Fetch stream info to get the URL
      const { data: stream } = await supabaseAdmin
        .from('cctv_streams')
        .select('stream_url, stream_type')
        .eq('id', stream_id)
        .single();

      if (stream) {
        // For HTTP streams, the URL itself may serve an image/snapshot
        analysisUrl = stream.stream_url;
      }
    }

    if (!analysisUrl) {
      return res.status(400).json({ error: 'Could not determine image source. Provide image_url or ensure stream URL is accessible.' });
    }

    // Call ML service to analyze frame
    let analysisResult = {};
    try {
      const response = await axios.post(`${ML_URL}/ml/analyze-image`, {
        image_url: analysisUrl
      }, { timeout: 30000 });
      analysisResult = response.data;
    } catch (mlErr) {
      return res.status(503).json({ error: 'ML service unavailable', details: mlErr.message });
    }

    // Update stream with latest analysis
    await supabaseAdmin
      .from('cctv_streams')
      .update({
        last_analysis: analysisResult,
        last_analyzed_at: new Date().toISOString()
      })
      .eq('id', stream_id);

    // If hazards detected, auto-create complaints
    if (analysisResult.detections && analysisResult.detections.length > 0) {
      const { data: stream } = await supabaseAdmin
        .from('cctv_streams')
        .select('latitude, longitude, name')
        .eq('id', stream_id)
        .single();

      for (const detection of analysisResult.detections) {
        await supabaseAdmin
          .from('complaints')
          .insert({
            title: `[CCTV Alert] ${detection.label.replace(/_/g, ' ')} detected at ${stream?.name || 'CCTV'}`,
            description: `Automated detection from CCTV stream "${stream?.name}". Confidence: ${(detection.confidence * 100).toFixed(1)}%. This complaint was auto-generated by the AI monitoring system.`,
            category: detection.label,
            latitude: stream?.latitude || 0,
            longitude: stream?.longitude || 0,
            severity: detection.confidence > 0.8 ? 'high' : 'medium',
            status: 'under_review',
            ai_analysis: { source: 'cctv', stream_id, detection },
            ai_detected_labels: [detection.label]
          });
      }
    }

    res.json({
      message: 'Frame analyzed',
      analysis: analysisResult,
      alertsCreated: (analysisResult.detections || []).length
    });
  } catch (err) { next(err); }
};

/**
 * POST /api/cctv/upload-video — Upload video for analysis
 */
exports.uploadVideo = async (req, res, next) => {
  try {
    if (!req.files || req.files.length === 0) {
      return res.status(400).json({ error: 'video file is required' });
    }

    const videoFile = req.files[0];
    const stream_id = req.body.stream_id;
    const latitude = req.body.latitude ? parseFloat(req.body.latitude) : null;
    const longitude = req.body.longitude ? parseFloat(req.body.longitude) : null;

    // Upload video to Supabase Storage
    const fileName = `cctv-${Date.now()}-${Math.random().toString(36).slice(2)}.mp4`;
    const { error: uploadError } = await supabaseAdmin.storage
      .from('complaint-videos')
      .upload(fileName, videoFile.buffer, { contentType: videoFile.mimetype });

    if (uploadError) {
      return res.status(500).json({ error: 'Failed to upload video: ' + uploadError.message });
    }

    const { data: urlData } = supabaseAdmin.storage
      .from('complaint-videos')
      .getPublicUrl(fileName);

    // Send to ML for analysis
    let analysisResult = {};
    try {
      const formData = new FormData();
      formData.append('video', videoFile.buffer, { filename: 'video.mp4', contentType: videoFile.mimetype });

      const response = await axios.post(`${ML_URL}/ml/analyze-video`, formData, {
        headers: formData.getHeaders(),
        timeout: 60000,
        maxContentLength: 50 * 1024 * 1024
      });
      analysisResult = response.data;
    } catch (mlErr) {
      console.warn('ML video analysis failed:', mlErr.message);
      analysisResult = { error: 'ML analysis unavailable', frames_analyzed: 0 };
    }

    // Auto-create complaint if hazards detected
    const agg = analysisResult.aggregated;
    if (agg && agg.top_label) {
      await supabaseAdmin
        .from('complaints')
        .insert({
          title: agg.title || `[Video] ${agg.top_label.replace(/_/g, ' ')} Detected`,
          description: `Detected via uploaded video analysis. ${agg.total_detections} detections across ${analysisResult.frames_analyzed} frames.`,
          category: agg.top_label,
          latitude: latitude || 0,
          longitude: longitude || 0,
          severity: agg.severity || 'medium',
          status: 'under_review',
          ai_analysis: { source: 'video_upload', videoUrl: urlData.publicUrl, ...analysisResult },
          ai_detected_labels: Object.keys(agg.label_counts || {})
        });
    }

    res.json({
      message: 'Video uploaded and analyzed',
      videoUrl: urlData.publicUrl,
      analysis: analysisResult
    });
  } catch (err) { next(err); }
};

/**
 * GET /api/cctv/alerts — Recent CCTV-generated alerts
 */
exports.getAlerts = async (req, res, next) => {
  try {
    const { data, error } = await supabaseAdmin
      .from('complaints')
      .select('*, departments(name, code)')
      .or('ai_analysis->>source.eq.cctv,ai_analysis->>source.eq.video_upload')
      .order('created_at', { ascending: false })
      .limit(50);

    if (error) return res.status(500).json({ error: error.message });

    res.json({ alerts: data || [] });
  } catch (err) { next(err); }
};
